---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  tasks:
    - import_tasks: tasks/chocolatey.yml
      tags: ["choco"]
    - import_tasks: tasks/wsl2.yml
      when: install_wsl2
      tags: ["wsl"]
    - import_tasks: tasks/desktop.yml
      when: remove_desktop_icons
      tags: ["desktop"]
    - import_tasks: tasks/explorer.yml
      when: configure_explorer
      tags: ["explorer"]
    - import_tasks: tasks/taskbar.yml
      when: configure_taskbar
      tags: ["taskbar"]
    - import_tasks: tasks/hostname.yml
      when: configure_hostname
      tags: ["hostname"]
