---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ["always"]

  tasks:
    - import_tasks: tasks/hostname.yml
      when: configure_hostname
      tags: ["hostname"]

    - import_tasks: tasks/updates.yml
      when: install_windows_updates
      tags: ["updates"]

    - import_tasks: tasks/debloat.yml
      when: remove_bloatware
      tags: ["debloat"]

    - import_tasks: tasks/chocolatey.yml
      tags: ["choco"]

    - import_tasks: tasks/windows_features.yml
      when: install_windows_features
      tags: ["windows_features"]

    - import_tasks: tasks/wsl2.yml
      when: install_wsl2
      tags: ["wsl"]

    - import_tasks: tasks/fonts.yml
      when: install_fonts
      tags: ["fonts"]

    - import_tasks: tasks/ohmyposh.yml
      when: install_ohmyposh
      tags: ["ohmyposh"]

    - import_tasks: tasks/explorer.yml
      when: configure_explorer
      tags: ["explorer"]

    - import_tasks: tasks/taskbar.yml
      when: configure_taskbar
      tags: ["taskbar"]

    - import_tasks: tasks/start_menu.yml
      when: configure_start_menu
      tags: ["start_menu"]

    - import_tasks: tasks/sounds.yml
      when: set_sound_scheme
      tags: ["sounds"]

    - import_tasks: tasks/mouse.yml
      when: disable_mouse_acceleration
      tags: ["mouse"]

    - import_tasks: tasks/power_plan.yml
      when: change_power_plan
      tags: ["power"]

    - import_tasks: tasks/remote_desktop.yml
      tags: ["remote_desktop"]

    - import_tasks: tasks/desktop.yml
      when: remove_desktop_icons
      tags: ["desktop"]

    - import_tasks: tasks/defrag.yml
      when: defrag_volumes
      tags: ["defrag"]
