---
- name: Ensure configured Chocolatey packages are installed.
  win_chocolatey:
    name: "{{ item.name | default(item) }}"
    ignore_checksums: yes
    state: present
  loop: "{{ choco_installed_packages }}"
