---
- name: Ensure configured Chocolatey packages are installed.
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.name | default(item) }}"
    ignore_checksums: true
    state: present
  loop: "{{ choco_installed_packages }}"

- name: Upgrade installed Chocolatey packages.
  chocolatey.chocolatey.win_chocolatey:
    name: all
    state: latest

- name: Clean chocolatey and nuget cache.
  ansible.windows.win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - '%UserProfile%\AppData\Local\Temp\chocolatey\'
    - '%UserProfile%\AppData\Local\Temp\nuget\'
    - '%UserProfile%\AppData\Local\NuGet\Cache\'
