---
- name: Ensure configured Chocolatey packages are installed.
  win_chocolatey:
    name: "{{ item.name | default(item) }}"
    ignore_checksums: true
    state: present
  loop: "{{ choco_installed_packages }}"

- name: Upgrade installed Chocolatey packages.
  win_chocolatey:
    name: all
    state: latest
