---
- name: Ensure configured Chocolatey packages are installed.
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    choco_args: "{{ item.choco_args | default(omit) }}"
  loop: "{{ choco_installed_packages }}"

- name: Clean chocolatey and nuget cache.
  ansible.windows.win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - '%UserProfile%\AppData\Local\Temp\chocolatey\'
    - '%UserProfile%\AppData\Local\Temp\nuget\'
    - '%UserProfile%\AppData\Local\NuGet\Cache\'
