---
- name: Ensure mouse acceleration is disabled.
  ansible.windows.win_regedit:
    path: HKCU:\Control Panel\Mouse
    name: "{{ item }}"
    data: 0
    type: string
  loop:
    - MouseSpeed
    - MouseThreshold1
    - MouseThreshold2
