---
- name: "Set power plan to {{ power_plan }}"
  vars:
    plans:
      high_performance: "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"
      balanced: "381b4222-f694-41f0-9685-ff5bb260df2e"
      power_saver: "a1841308-3541-4fab-bc81-f71556f20b4a"
  community.windows.win_power_plan:
    guid: "{{ plans[power_plan] | default(balanced) }}"
