---
- name: Ensure Automatic Install of Suggested Apps disabled.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SilentInstalledAppsEnabled
    data: 0
    type: dword

- name: Ensure App Suggestions in Start menu disabled.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SystemPaneSuggestionsEnabled
    data: 0
    type: dword

- name: Ensure popup "tips" about Windows disabled.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: SoftLandingEnabled
    data: 0
    type: dword

- name: Ensure 'Windows Welcome Experience' disabled.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
    name: "{{ item }}"
    data: 0
    type: dword
  loop:
    - SubscribedContent-310093Enabled
    - SubscribedContent-338388Enabled
    - SubscribedContent-338389Enabled
    - SubscribedContent-88000326Enabled
