---
- name: Ensure 'Search' unpinned from Taskbar.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Search
    name: SearchboxTaskbarMode
    data: 0
    type: dword

- name: Ensure Task View, Chat and Cortana are unpinned from Taskbar.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: "{{ item }}"
    data: 0
    type: dword
  loop:
    - ShowTaskViewButton
    - TaskbarMn
    - ShowCortanaButton

- name: Ensure 'News and Interests' unpinned from Taskbar.
  ansible.windows.win_regedit:
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Feeds
    name: ShellFeedsTaskbarViewMode
    data: 2
    type: dword
