---
- name: Check for missing updates.
  ansible.windows.win_updates:
    state: searched

- name: Install Windows updates.
  ansible.windows.win_updates:
    category_names: "{{ update_categories | default(omit) }}"
    reboot: "{{ windows_updates_reboot | default(false) }}"
  register: update_result
  until: update_result.found_update_count == 0
