---
- name: Enable Windows optional features.
  ansible.windows.win_optional_feature:
    name: "{{ windows_feature.key }}"
    state: "{{ 'present' if windows_feature.value else 'absent' }}"
    include_parent: true
  loop: "{{ windows_features | dict2items }}"
  loop_control:
    loop_var: windows_feature
  register: feature_status

- name: Reboot if Windows optional feature requires it.
  ansible.windows.win_reboot:
  when: item.reboot_required
  loop: "{{ feature_status.results }}"
